### ISSUE TITLE
.net standard support

### ISSUE THREAD

**Issue by uriah-chs** [thycotic/uipath-orchestrator-tss#2]
It seems like maybe this doesn't work with the latest version of UIPath which is built for dotnet core.  Are there plans to update the project?

**Comment by adchatakora** [comment]
In an attempt to upgrade orchestrator to the latest version we ran into this issue
Plugin 'SecretServer.SecureStore.dll' specified in the Orchestrator configuration is not compatible with the new version of Orchestrator. Target framework '.NETFramework,Version=v4.7.2' is not in the supported list (see online documentation).
Per the release notes here https://docs.uipath.com/releasenotes/docs/orchestrator-2020-10-1 , The TargetFramework must be upgraded from the previous .NET Framework 4.7.2 to a supported Target Frameworks to maintain Credential Store Plugins and NLog extensions functionality. Check the Target Framework docs for details.

Are there any plans top do this? We love and rely heavily on this plugin for a lot of our processes as it allows us to keep the credentials safe in SS.  2 months ago changes were made in this PR https://github.com/thycotic/uipath-orchestrator-tss/commit/67ed982bddbde0537ffc664fb2f2ff6c5fa3447a . If that is the applicable changes, anyway we can get a new .dll file?
Thanks you very much
![Screen Shot 2020-12-03 at 2 00 33 PM](https://user-images.githubusercontent.com/75447711/101075607-411d9880-3570-11eb-9f6d-a0848a06c52e.png)

**Comment by hansboder** [comment]
A new release build is available that has been updated to work with the new version of UIPath.
